services:
  frontend:
    build:
      context: ../frontend
    container_name: frontend
    networks:
      - app-net

  java-backend:
    build:
      context: ../java-backend
    container_name: java-backend
    networks:
      - app-net

  python-backend:
    build:
      context: ../python-backend
    container_name: python-backend
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - java-backend
      - python-backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
