version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    expose:
      - "3000"
    networks:
      - app-network

  java-backend:
    build: ./java-backend
    container_name: java-backend
    restart: always
    expose:
      - "8080"    # Spring Boot default
    networks:
      - app-network

  python-backend:
    build: ./python-backend
    container_name: python-backend
    restart: always
    expose:
      - "8000"    # ✅ changed from 5000 to 8000
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - java-backend
      - python-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
